### ISSUE TITLE
20170817_2.md文字错误反馈

### ISSUE THREAD

**Issue by VimWei** [lymslive/vimllearn#2]
z/20170817_2.md  以下语句的括号中内容有点不顺

> :if 命令（以后下一节要但要的 :while命令）

**Comment by VimWei** [comment]
下文中的**而且返回假**，应该是**否则返回假**？

> 然而，我们还是经常需要判断其他类型的值的某种状态的。这时可以利用一个内建函数
> `empty()` 来帮忙。它可以接收任何类型的一个参数，如果它是“空”的，就返回真（
> `v:true`），而且返回假（'v:false'）。在很大程度上，它可以代替直接使用 `:if` 的
> 条件表达式，只不过在值上恰好是逻辑取反；优点则是写法统一，适用于所有类型。

**Comment by lymslive** [comment]
已修改。第一条“以后”是“以及”的笔误。
